// Automatically generated by gen.pl, don't edit #	<remove the line>

#define	DNSMASQ_SUPPORT	1
#define	CONFIG_DNSMASQ	y
#define	__CONFIG_DNSMASQ__	1
//#define	LOG_DNSMASQ	0 	<remove the line>
//#define	UDHCPD_SUPPORT	0	<remove the line>
//#define	CONFIG_UDHCPD		<remove the line>
#undef	__CONFIG_UDHCPD__
//#define	UDHCPC_SUPPORT	0	<remove the line>
//#define	CONFIG_UDHCPC		<remove the line>
#undef	__CONFIG_UDHCPC__
//#define	LOG_DHCPD	0 	<remove the line>
//#define	LOG_DHCPC	0 	<remove the line>
#define	PPPOE_SUPPORT	1
#define	CONFIG_PPPOE	y
#define	__CONFIG_PPPOE__	1
//#define	LOG_PPPOE	0 	<remove the line>
#define	PPTP_SUPPORT	1
#define	CONFIG_PPTP	y
#define	__CONFIG_PPTP__	1
#define	PPTP_DHCPC_SUPPORT	1
#define	CONFIG_PPTP_DHCPC	y
#define	__CONFIG_PPTP_DHCPC__	1
//#define	LOG_PPTP	0 	<remove the line>
#define	L2TP_SUPPORT	1
#define	CONFIG_L2TP	y
#define	__CONFIG_L2TP__	1
//#define	LOG_L2TP	0 	<remove the line>
#define	PPPD_SUPPORT	1
#define	CONFIG_PPPD	y
#define	__CONFIG_PPPD__	1
//#define	LOG_PPPD	0 	<remove the line>
//#define	ROUTED_SUPPORT	0	<remove the line>
//#define	CONFIG_ROUTED		<remove the line>
#undef	__CONFIG_ROUTED__
#define	ZEBRA_SUPPORT	1
#define	CONFIG_ZEBRA	y
#define	__CONFIG_ZEBRA__	1
//#define	LOG_ZEBRA	0 	<remove the line>
#define	TFTPD_SUPPORT	1
#define	CONFIG_TFTPD	y
#define	__CONFIG_TFTPD__	1
//#define	LOG_TFTPD	0 	<remove the line>
#define	DDNS_SUPPORT	1
#define	CONFIG_DDNS	y
#define	__CONFIG_DDNS__	1
//#define	LOG_DDNS	0 	<remove the line>
#define	TZO_WEB_CLIENT2_SUPPORT	1
#define	CONFIG_TZO_WEB_CLIENT2	y
#define	__CONFIG_TZO_WEB_CLIENT2__	1
#define	CRON_SUPPORT	1
#define	CONFIG_CRON	y
#define	__CONFIG_CRON__	1
//#define	LOG_CRON	0 	<remove the line>
#define	HTTPD_SUPPORT	1
#define	CONFIG_HTTPD	y
#define	__CONFIG_HTTPD__	1
#define	GET_POST_SUPPORT	1
#define	CONFIG_GET_POST	y
#define	__CONFIG_GET_POST__	1
//#define	LOG_HTTPD	0 	<remove the line>
//#define	CUSTOM404_SUPPORT	0	<remove the line>
//#define	CONFIG_CUSTOM404		<remove the line>
#undef	__CONFIG_CUSTOM404__
#define	TRENDMICRO_SSS_SUPPORT	1
#define	CONFIG_TRENDMICRO_SSS	y
#define	__CONFIG_TRENDMICRO_SSS__	1
#define	HNAP_SUPPORT	1
#define	CONFIG_HNAP	y
#define	__CONFIG_HNAP__	1
#define	HNAP_SSDPDISCOVERY_SUPPORT	1
#define	CONFIG_HNAP_SSDPDISCOVERY	y
#define	__CONFIG_HNAP_SSDPDISCOVERY__	1
//#define	HNAP_SPEC_V11_SUPPORT	0	<remove the line>
//#define	CONFIG_HNAP_SPEC_V11		<remove the line>
#undef	__CONFIG_HNAP_SPEC_V11__
#define	HNAP_SPEC_V12_SUPPORT	1
#define	CONFIG_HNAP_SPEC_V12	y
#define	__CONFIG_HNAP_SPEC_V12__	1
#define	HNAP_DHCP_RESERVATIONS_SUPPORT	1
#define	CONFIG_HNAP_DHCP_RESERVATIONS	y
#define	__CONFIG_HNAP_DHCP_RESERVATIONS__	1
#define	EXPAT_SUPPORT	1
#define	CONFIG_EXPAT	y
#define	__CONFIG_EXPAT__	1
#define	HEARTBEAT_SUPPORT	1
#define	CONFIG_HEARTBEAT	y
#define	__CONFIG_HEARTBEAT__	1
//#define	LOG_HEARTBEAT	0 	<remove the line>
#define	HTTPS_SUPPORT	1
#define	CONFIG_HTTPS	y
#define	__CONFIG_HTTPS__	1
#define	MULTICAST_SUPPORT	1
#define	CONFIG_MULTICAST	y
#define	__CONFIG_MULTICAST__	1
#define	IGMP_X_MLD_SUPPORT	1
#define	CONFIG_IGMP_X_MLD	y
#define	__CONFIG_IGMP_X_MLD__	1
#define	IGMPV3_SUPPORT	1
#define	CONFIG_IGMPV3	y
#define	__CONFIG_IGMPV3__	1
#define	IGMP_HOSTTRACK_SUPPORT	1
#define	CONFIG_IGMP_HOSTTRACK	y
#define	__CONFIG_IGMP_HOSTTRACK__	1
//#define	SETUP_WIZARD_SUPPORT	0	<remove the line>
//#define	CONFIG_SETUP_WIZARD		<remove the line>
#undef	__CONFIG_SETUP_WIZARD__
#define	PUSH_BUTTON_TEST_SUPPORT	1
#define	CONFIG_PUSH_BUTTON_TEST	y
#define	__CONFIG_PUSH_BUTTON_TEST__	1
#define	SINGLE_FORWARD_SUPPORT	1
#define	CONFIG_SINGLE_FORWARD	y
#define	__CONFIG_SINGLE_FORWARD__	1
#define	UDHCPD_STATIC_SUPPORT	1
#define	CONFIG_UDHCPD_STATIC	y
#define	__CONFIG_UDHCPD_STATIC__	1
#define	XBOX_SUPPORT	1
#define	CONFIG_XBOX	y
#define	__CONFIG_XBOX__	1
#define	BACKUP_RESTORE_SUPPORT	1
#define	CONFIG_BACKUP_RESTORE	y
#define	__CONFIG_BACKUP_RESTORE__	1
#define	PORT_TRIGGER_SUPPORT	1
#define	CONFIG_PORT_TRIGGER	y
#define	__CONFIG_PORT_TRIGGER__	1
#define	HW_QOS_SUPPORT	1
#define	CONFIG_HW_QOS	y
#define	__CONFIG_HW_QOS__	1
#define	SW_QOS_SUPPORT	1
#define	CONFIG_SW_QOS	y
#define	__CONFIG_SW_QOS__	1
#define	WRITE_MAC_SUPPORT	1
#define	CONFIG_WRITE_MAC	y
#define	__CONFIG_WRITE_MAC__	1
#define	WRITE_SN_SUPPORT	1
#define	CONFIG_WRITE_SN	y
#define	__CONFIG_WRITE_SN__	1
#define	WRITE_COUNTRY_SUPPORT	1
#define	CONFIG_WRITE_COUNTRY	y
#define	__CONFIG_WRITE_COUNTRY__	1
#define	WRITE_PA_SUPPORT	1
#define	CONFIG_WRITE_PA	y
#define	__CONFIG_WRITE_PA__	1
#define	BOOTNV_SUPPORT	1
#define	CONFIG_BOOTNV	y
#define	__CONFIG_BOOTNV__	1
#define	MFGTEST_SUPPORT	1
#define	CONFIG_MFGTEST	y
#define	__CONFIG_MFGTEST__	1
#define	DIAG_SUPPORT	1
#define	CONFIG_DIAG	y
#define	__CONFIG_DIAG__	1
#define	BOOT_DHCPD_SUPPORT	1
#define	CONFIG_BOOT_DHCPD	y
#define	__CONFIG_BOOT_DHCPD__	1
#define	BOOT_HTTPD_SUPPORT	1
#define	CONFIG_BOOT_HTTPD	y
#define	__CONFIG_BOOT_HTTPD__	1
#define	WIRELESS_SUPPORT	1
#define	CONFIG_WIRELESS	y
#define	__CONFIG_WIRELESS__	1
//#define	EOU_SUPPORT	0	<remove the line>
//#define	CONFIG_EOU		<remove the line>
#undef	__CONFIG_EOU__
//#define	WCN_SUPPORT	0	<remove the line>
//#define	CONFIG_WCN		<remove the line>
#undef	__CONFIG_WCN__
//#define	WCN2_SUPPORT	0	<remove the line>
//#define	CONFIG_WCN2		<remove the line>
#undef	__CONFIG_WCN2__
#define	WSC_SUPPORT	1
#define	CONFIG_WSC	y
#define	__CONFIG_WSC__	1
#define	WRITE_WSC_PIN_SUPPORT	1
#define	CONFIG_WRITE_WSC_PIN	y
#define	__CONFIG_WRITE_WSC_PIN__	1
//#define	WSC_C_SUPPORT	0	<remove the line>
//#define	CONFIG_WSC_C		<remove the line>
#undef	__CONFIG_WSC_C__
//#define	WSC_CPLUS_SUPPORT	0	<remove the line>
//#define	CONFIG_WSC_CPLUS		<remove the line>
#undef	__CONFIG_WSC_CPLUS__
//#define	XYSSL_SUPPORT	0	<remove the line>
//#define	CONFIG_XYSSL		<remove the line>
#undef	__CONFIG_XYSSL__
#define	POLARSSL_SUPPORT	1
#define	CONFIG_POLARSSL	y
#define	__CONFIG_POLARSSL__	1
//#define	EZC_SUPPORT	0	<remove the line>
//#define	CONFIG_EZC		<remove the line>
#undef	__CONFIG_EZC__
//#define	SES_SUPPORT	0	<remove the line>
//#define	CONFIG_SES		<remove the line>
#undef	__CONFIG_SES__
//#define	SES_BUTTON_SUPPORT	0	<remove the line>
//#define	CONFIG_SES_BUTTON		<remove the line>
#undef	__CONFIG_SES_BUTTON__
//#define	AOSS_SUPPORT	0	<remove the line>
//#define	CONFIG_AOSS		<remove the line>
#undef	__CONFIG_AOSS__
//#define	SPEED_BOOSTER_SUPPORT	0	<remove the line>
//#define	CONFIG_SPEED_BOOSTER		<remove the line>
#undef	__CONFIG_SPEED_BOOSTER__
//#define	DISABLE_11N_40M_SUPPORT	0	<remove the line>
//#define	CONFIG_DISABLE_11N_40M		<remove the line>
#undef	__CONFIG_DISABLE_11N_40M__
//#define	WIRELESS_5G_BAND_SUPPORT	0	<remove the line>
//#define	CONFIG_WIRELESS_5G_BAND		<remove the line>
#undef	__CONFIG_WIRELESS_5G_BAND__
//#define	SELE_DUAL_BAND_SUPPORT	0	<remove the line>
//#define	CONFIG_SELE_DUAL_BAND		<remove the line>
#undef	__CONFIG_SELE_DUAL_BAND__
//#define	SIMUL_DUAL_BAND_SUPPORT	0	<remove the line>
//#define	CONFIG_SIMUL_DUAL_BAND		<remove the line>
#undef	__CONFIG_SIMUL_DUAL_BAND__
#define	MONITOR_USB_SUPPORT	1
#define	CONFIG_MONITOR_USB	y
#define	__CONFIG_MONITOR_USB__	1
//#define	MULTIPLE_LOGIN_SUPPORT	0	<remove the line>
//#define	CONFIG_MULTIPLE_LOGIN		<remove the line>
#undef	__CONFIG_MULTIPLE_LOGIN__
//#define	TINYLOGIN_SUPPORT	0	<remove the line>
//#define	CONFIG_TINYLOGIN		<remove the line>
#undef	__CONFIG_TINYLOGIN__
#define	BUSYBOX_LOGIN_SUPPORT	1
#define	CONFIG_BUSYBOX_LOGIN	y
#define	__CONFIG_BUSYBOX_LOGIN__	1
#define	PARAGON_NTFS_SUPPORT	1
#define	CONFIG_PARAGON_NTFS	y
#define	__CONFIG_PARAGON_NTFS__	1
#define	STORAGE_SUPPORT	1
#define	CONFIG_STORAGE	y
#define	__CONFIG_STORAGE__	1
//#define	SMB302_SUPPORT	0	<remove the line>
//#define	CONFIG_SMB302		<remove the line>
#undef	__CONFIG_SMB302__
//#define	SMB3025_SUPPORT	0	<remove the line>
//#define	CONFIG_SMB3025		<remove the line>
#undef	__CONFIG_SMB3025__
#define	SMB3215_SUPPORT	1
#define	CONFIG_SMB3215	y
#define	__CONFIG_SMB3215__	1
#define	NMBD_NAME_REGISTER_SUPPORT	1
#define	CONFIG_NMBD_NAME_REGISTER	y
#define	__CONFIG_NMBD_NAME_REGISTER__	1
#define	FTP_SUPPORT	1
#define	CONFIG_FTP	y
#define	__CONFIG_FTP__	1
#define	VSFTPD_SUPPORT	1
#define	CONFIG_VSFTPD	y
#define	__CONFIG_VSFTPD__	1
//#define	PROFTPD_SUPPORT	0	<remove the line>
//#define	CONFIG_PROFTPD		<remove the line>
#undef	__CONFIG_PROFTPD__
//#define	MEDIA_SERVER_SUPPORT	0	<remove the line>
//#define	CONFIG_MEDIA_SERVER		<remove the line>
#undef	__CONFIG_MEDIA_SERVER__
//#define	EMAIL_ALERT_SUPPORT	0	<remove the line>
//#define	CONFIG_EMAIL_ALERT		<remove the line>
#undef	__CONFIG_EMAIL_ALERT__
//#define	PRINTER_SERVER_SUPPORT	0	<remove the line>
//#define	CONFIG_PRINTER_SERVER		<remove the line>
#undef	__CONFIG_PRINTER_SERVER__
#define	TCP_WRAPPER_SUPPORT	1
#define	CONFIG_TCP_WRAPPER	y
#define	__CONFIG_TCP_WRAPPER__	1
#define	POPT_SUPPORT	1
#define	CONFIG_POPT	y
#define	__CONFIG_POPT__	1
#define	RAID_SUPPORT	1
#define	CONFIG_RAID	y
#define	__CONFIG_RAID__	1
//#define	GMP_SUPPORT	0	<remove the line>
//#define	CONFIG_GMP		<remove the line>
#undef	__CONFIG_GMP__
#define	MKDOSFS_SUPPORT	1
#define	CONFIG_MKDOSFS	y
#define	__CONFIG_MKDOSFS__	1
#define	DOSFSTOOLS_SUPPORT	1
#define	CONFIG_DOSFSTOOLS	y
#define	__CONFIG_DOSFSTOOLS__	1
#define	RESPART_SUPPORT	1
#define	CONFIG_RESPART	y
#define	__CONFIG_RESPART__	1
#define	ARCHIVE_SUPPORT	1
#define	CONFIG_ARCHIVE	y
#define	__CONFIG_ARCHIVE__	1
#define	DISCONNECT_DISK_SUPPORT	1
#define	CONFIG_DISCONNECT_DISK	y
#define	__CONFIG_DISCONNECT_DISK__	1
#define	USER_GROUP_SUPPORT	1
#define	CONFIG_USER_GROUP	y
#define	__CONFIG_USER_GROUP__	1
#define	USER_NOTE_SUPPORT	1
#define	CONFIG_USER_NOTE	y
#define	__CONFIG_USER_NOTE__	1
#define	WIPEDISKS_SUPPORT	1
#define	CONFIG_WIPEDISKS	y
#define	__CONFIG_WIPEDISKS__	1
#define	DISKTESTWAIT_SUPPORT	1
#define	CONFIG_DISKTESTWAIT	y
#define	__CONFIG_DISKTESTWAIT__	1
//#define	SECSRL_SUPPORT	0	<remove the line>
//#define	CONFIG_SECSRL		<remove the line>
#undef	__CONFIG_SECSRL__
//#define	SEUTIL_SUPPORT	0	<remove the line>
//#define	CONFIG_SEUTIL		<remove the line>
#undef	__CONFIG_SEUTIL__
//#define	NFS_SUPPORT	0	<remove the line>
//#define	CONFIG_NFS		<remove the line>
#undef	__CONFIG_NFS__
//#define	PORTMAP_SUPPORT	0	<remove the line>
//#define	CONFIG_PORTMAP		<remove the line>
#undef	__CONFIG_PORTMAP__
//#define	MPPPOE_SUPPORT	0	<remove the line>
//#define	CONFIG_MPPPOE		<remove the line>
#undef	__CONFIG_MPPPOE__
//#define	LOG_MPPPOE	0 	<remove the line>
//#define	UNNUMBERIP_SUPPORT	0	<remove the line>
//#define	CONFIG_UNNUMBERIP		<remove the line>
#undef	__CONFIG_UNNUMBERIP__
//#define	LOG_UNNUMBERIP	0 	<remove the line>
//#define	DDNS3322_SUPPORT	0	<remove the line>
//#define	CONFIG_DDNS3322		<remove the line>
#undef	__CONFIG_DDNS3322__
//#define	LOG_DDNS3322	0 	<remove the line>
//#define	PEANUTHULL_SUPPORT	0	<remove the line>
//#define	CONFIG_PEANUTHULL		<remove the line>
#undef	__CONFIG_PEANUTHULL__
//#define	LOG_PEANUTHULL	0 	<remove the line>
//#define	MULTILANG_SUPPORT	0	<remove the line>
//#define	CONFIG_MULTILANG		<remove the line>
#undef	__CONFIG_MULTILANG__
#define	MULTILANG_PAGE_SUPPORT	1
#define	CONFIG_MULTILANG_PAGE	y
#define	__CONFIG_MULTILANG_PAGE__	1
#define	MULTILANG_GUI_SUPPORT	1
#define	CONFIG_MULTILANG_GUI	y
#define	__CONFIG_MULTILANG_GUI__	1
#define	VLAN_SUPPORT	1
#define	CONFIG_VLAN	y
#define	__CONFIG_VLAN__	1
//#define	PARENTAL_CONTROL_SUPPORT	0	<remove the line>
//#define	CONFIG_PARENTAL_CONTROL		<remove the line>
#undef	__CONFIG_PARENTAL_CONTROL__
//#define	LOG_PARENTAL_CONTROL	0 	<remove the line>
//#define	SNMP_SUPPORT	0	<remove the line>
//#define	CONFIG_SNMP		<remove the line>
#undef	__CONFIG_SNMP__
//#define	LOG_SNMP	0 	<remove the line>
//#define	DEBUG_SNMP	0 	<remove the line>
//#define	HSIAB_SUPPORT	0	<remove the line>
//#define	CONFIG_HSIAB		<remove the line>
#undef	__CONFIG_HSIAB__
//#define	LOG_HSIAB	0 	<remove the line>
//#define	DDM_SUPPORT	0	<remove the line>
//#define	CONFIG_DDM		<remove the line>
#undef	__CONFIG_DDM__
//#define	LOG_DDM	0 	<remove the line>
//#define	UTELNETD_SUPPORT	0	<remove the line>
//#define	CONFIG_UTELNETD		<remove the line>
#undef	__CONFIG_UTELNETD__
//#define	SYMC_OUTBREAK_SUPPORT	0	<remove the line>
//#define	CONFIG_SYMC_OUTBREAK		<remove the line>
#undef	__CONFIG_SYMC_OUTBREAK__
//#define	EBTABLES_SUPPORT	0	<remove the line>
//#define	CONFIG_EBTABLES		<remove the line>
#undef	__CONFIG_EBTABLES__
#define	LLTD_SUPPORT	1
#define	CONFIG_LLTD	y
#define	__CONFIG_LLTD__	1
//#define	HTTP_SIMPLE_SUPPORT	0	<remove the line>
//#define	CONFIG_HTTP_SIMPLE		<remove the line>
#undef	__CONFIG_HTTP_SIMPLE__
//#define	PCIUTILS_SUPPORT	0	<remove the line>
//#define	CONFIG_PCIUTILS		<remove the line>
#undef	__CONFIG_PCIUTILS__
#define	WL_IOCMD_SUPPORT	1
#define	CONFIG_WL_IOCMD	y
#define	__CONFIG_WL_IOCMD__	1
//#define	WL_FULL_SUPPORT	0	<remove the line>
//#define	CONFIG_WL_FULL		<remove the line>
#undef	__CONFIG_WL_FULL__
#define	SYSLOG_SUPPORT	1
#define	CONFIG_SYSLOG	y
#define	__CONFIG_SYSLOG__	1
#define	KLOGD_SUPPORT	1
#define	CONFIG_KLOGD	y
#define	__CONFIG_KLOGD__	1
//#define	WL_WDS_SUPPORT	0	<remove the line>
//#define	CONFIG_WL_WDS		<remove the line>
#undef	__CONFIG_WL_WDS__
//#define	WL_STA_SUPPORT	0	<remove the line>
//#define	CONFIG_WL_STA		<remove the line>
#undef	__CONFIG_WL_STA__
//#define	WAKE_ON_LAN_SUPPORT	0	<remove the line>
//#define	CONFIG_WAKE_ON_LAN		<remove the line>
#undef	__CONFIG_WAKE_ON_LAN__
//#define	SAMBA_SUPPORT	0	<remove the line>
//#define	CONFIG_SAMBA		<remove the line>
#undef	__CONFIG_SAMBA__
//#define	UPNP_FORWARD_SUPPORT	0	<remove the line>
//#define	CONFIG_UPNP_FORWARD		<remove the line>
#undef	__CONFIG_UPNP_FORWARD__
//#define	PERFORMANCE_SUPPORT	0	<remove the line>
//#define	CONFIG_PERFORMANCE		<remove the line>
#undef	__CONFIG_PERFORMANCE__
//#define	PPPOE_SERVER_SUPPORT	0	<remove the line>
//#define	CONFIG_PPPOE_SERVER		<remove the line>
#undef	__CONFIG_PPPOE_SERVER__
//#define	AOL_SUPPORT	0	<remove the line>
//#define	CONFIG_AOL		<remove the line>
#undef	__CONFIG_AOL__
//#define	EMI_TEST_SUPPORT	0	<remove the line>
//#define	CONFIG_EMI_TEST		<remove the line>
#undef	__CONFIG_EMI_TEST__
//#define	DEBUG_WEB	0 	<remove the line>
//#define	DEBUG_RC	0 	<remove the line>
//#define	BRCM	0 	<remove the line>
//#define	MY_DEBUG	0 	<remove the line>
//#define	THROUGHPUT_TEST_SUPPORT	0	<remove the line>
//#define	CONFIG_THROUGHPUT_TEST		<remove the line>
#undef	__CONFIG_THROUGHPUT_TEST__
//#define	FOR_WAN_PORT	0 	<remove the line>
//#define	FOR_TMOBILE_TEST_SUPPORT	0	<remove the line>
//#define	CONFIG_FOR_TMOBILE_TEST		<remove the line>
#undef	__CONFIG_FOR_TMOBILE_TEST__
//#define	CURL_SUPPORT	0	<remove the line>
//#define	CONFIG_CURL		<remove the line>
#undef	__CONFIG_CURL__
//#define	T_MOBILE_SUPPORT	0	<remove the line>
//#define	CONFIG_T_MOBILE		<remove the line>
#undef	__CONFIG_T_MOBILE__
//#define	RXP_SUPPORT	0	<remove the line>
//#define	CONFIG_RXP		<remove the line>
#undef	__CONFIG_RXP__
//#define	T_CERT_SUPPORT	0	<remove the line>
//#define	CONFIG_T_CERT		<remove the line>
#undef	__CONFIG_T_CERT__
//#define	CELL_VENDOR_TEST_SUPPORT	0	<remove the line>
//#define	CONFIG_CELL_VENDOR_TEST		<remove the line>
#undef	__CONFIG_CELL_VENDOR_TEST__
//#define	DUAL_IMAGE_SUPPORT	0	<remove the line>
//#define	CONFIG_DUAL_IMAGE		<remove the line>
#undef	__CONFIG_DUAL_IMAGE__
#define	IGMP_SNOOP_SUPPORT	1
#define	CONFIG_IGMP_SNOOP	y
#define	__CONFIG_IGMP_SNOOP__	1
#define	EMF_SUPPORT	1
#define	CONFIG_EMF	y
#define	__CONFIG_EMF__	1
#define	IPV6_SUPPORT	1
#define	CONFIG_IPV6	y
#define	__CONFIG_IPV6__	1
#define	RADVD_SUPPORT	1
#define	CONFIG_RADVD	y
#define	__CONFIG_RADVD__	1
#define	IPROUTE2_SUPPORT	1
#define	CONFIG_IPROUTE2	y
#define	__CONFIG_IPROUTE2__	1
#define	IPUTILS_SUPPORT	1
#define	CONFIG_IPUTILS	y
#define	__CONFIG_IPUTILS__	1
#define	DHCPV6S_SUPPORT	1
#define	CONFIG_DHCPV6S	y
#define	__CONFIG_DHCPV6S__	1
#define	DHCPV6C_SUPPORT	1
#define	CONFIG_DHCPV6C	y
#define	__CONFIG_DHCPV6C__	1
//#define	TWONKY_SUPPORT	0	<remove the line>
//#define	CONFIG_TWONKY		<remove the line>
#undef	__CONFIG_TWONKY__
//#define	BOOT128K_SUPPORT	0	<remove the line>
//#define	CONFIG_BOOT128K		<remove the line>
#undef	__CONFIG_BOOT128K__
//#define	EGHN_SUPPORT	0	<remove the line>
//#define	CONFIG_EGHN		<remove the line>
#undef	__CONFIG_EGHN__
#define	THREE_ARP_GRATUATOUS_SUPPORT	1
#define	CONFIG_THREE_ARP_GRATUATOUS	y
#define	__CONFIG_THREE_ARP_GRATUATOUS__	1
#define	SELFSIGN_SUPPORT	1
#define	CONFIG_SELFSIGN	y
#define	__CONFIG_SELFSIGN__	1
//#define	BUILD_MFG_SUPPORT	0	<remove the line>
//#define	CONFIG_BUILD_MFG		<remove the line>
#undef	__CONFIG_BUILD_MFG__
//#define	WL_APP_SUPPORT	0	<remove the line>
//#define	CONFIG_WL_APP		<remove the line>
#undef	__CONFIG_WL_APP__
//#define	GUI_TIMEOUT_SUPPORT	0	<remove the line>
//#define	CONFIG_GUI_TIMEOUT		<remove the line>
#undef	__CONFIG_GUI_TIMEOUT__
#define	IPV6_SECURITY_SUPPORT	1
#define	CONFIG_IPV6_SECURITY	y
#define	__CONFIG_IPV6_SECURITY__	1
#define	ALG_MODULE_SUPPORT	1
#define	CONFIG_ALG_MODULE	y
#define	__CONFIG_ALG_MODULE__	1
#define	AUTO_DETECT_LANGUAGE_SUPPORT	1
#define	CONFIG_AUTO_DETECT_LANGUAGE	y
#define	__CONFIG_AUTO_DETECT_LANGUAGE__	1
#define	WIRELESS_WARNING_PAGE_SUPPORT	1
#define	CONFIG_WIRELESS_WARNING_PAGE	y
#define	__CONFIG_WIRELESS_WARNING_PAGE__	1
#define	GUEST_NETWORK_SUPPORT	1
#define	CONFIG_GUEST_NETWORK	y
#define	__CONFIG_GUEST_NETWORK__	1
#define	HOTSPOT_SUPPORT	1
#define	CONFIG_HOTSPOT	y
#define	__CONFIG_HOTSPOT__	1
#define	WAN_DETECT_SUPPORT	1
#define	CONFIG_WAN_DETECT	y
#define	__CONFIG_WAN_DETECT__	1
#define	CES_PARENTAL_CONTROL_SUPPORT	1
#define	CONFIG_CES_PARENTAL_CONTROL	y
#define	__CONFIG_CES_PARENTAL_CONTROL__	1
#define	CES_MDNS_SUPPORT	1
#define	CONFIG_CES_MDNS	y
#define	__CONFIG_CES_MDNS__	1
#define	CES_E_SERIES_SUPPORT	1
#define	CONFIG_CES_E_SERIES	y
#define	__CONFIG_CES_E_SERIES__	1
#define	ROUTER2SWITCH_SUPPORT	1
#define	CONFIG_ROUTER2SWITCH	y
#define	__CONFIG_ROUTER2SWITCH__	1
//#define	USBAP_SUPPORT	0	<remove the line>
//#define	CONFIG_USBAP		<remove the line>
#undef	__CONFIG_USBAP__
//#define	VIRTUAL_USB_SUPPORT	0	<remove the line>
//#define	CONFIG_VIRTUAL_USB		<remove the line>
#undef	__CONFIG_VIRTUAL_USB__
