#ifndef _LIBNET_PROTO_H_
#define _LIBNET_PROTO_H_

/* This file is automatically generated with "make proto". DO NOT EDIT */


/* The following definitions come from libnet/libnet_join.c  */

NTSTATUS libnet_join_ok(const char *netbios_domain_name,
			const char *machine_name,
			const char *dc_name);
WERROR libnet_init_JoinCtx(TALLOC_CTX *mem_ctx,
			   struct libnet_JoinCtx **r);
WERROR libnet_init_UnjoinCtx(TALLOC_CTX *mem_ctx,
			     struct libnet_UnjoinCtx **r);
WERROR libnet_join_rollback(TALLOC_CTX *mem_ctx,
			    struct libnet_JoinCtx *r);
WERROR libnet_Join(TALLOC_CTX *mem_ctx,
		   struct libnet_JoinCtx *r);
WERROR libnet_Unjoin(TALLOC_CTX *mem_ctx,
		     struct libnet_UnjoinCtx *r);

/* The following definitions come from libnet/libnet_samsync.c  */

NTSTATUS samsync_fix_delta_array(TALLOC_CTX *mem_ctx,
				 DATA_BLOB *session_key,
				 enum netr_SamDatabaseID database_id,
				 struct netr_DELTA_ENUM_ARRAY *r);

/* The following definitions come from librpc/gen_ndr/ndr_libnet_join.c  */

_PUBLIC_ void ndr_print_libnet_JoinCtx(struct ndr_print *ndr, const char *name, int flags, const struct libnet_JoinCtx *r);
_PUBLIC_ void ndr_print_libnet_UnjoinCtx(struct ndr_print *ndr, const char *name, int flags, const struct libnet_UnjoinCtx *r);

#endif /*  _LIBNET_PROTO_H_  */
