/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux localhost.localdomain 2.6.29.4-167.fc11.i686.PAE #1 SMP Wed May 27 17:28:22 EDT 2009 i686 i686 i386 GNU/Linux"
#define BUILD_ENV_DATE "Thu Dec 31 04:21:29 CST 2015"
#define BUILD_ENV_SRCDIR "."
#define BUILD_ENV_BUILDDIR "."
#define BUILD_ENV_USER "root"
#define BUILD_ENV_HOST "localhost.localdomain"
#define BUILD_ENV_COMPILER "mipsel-uclibc-linux26-gcc"
#endif /* _BUILD_ENV_H */
