# Copyright (C) 2009 - 2010, CyberTAN Corporation
#
# Copyright (C) 2009, CyberTAN Corporation
# All Rights Reserved.
#
# You can redistribute it and/or modify it under the terms of the GPL v2
#
#
# THIS SOFTWARE IS OFFERED "AS IS", AND CYBERTAN GRANTS NO WARRANTIES OF ANY
# KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE.
#
# CYBERTAN SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A SPECIFIC PURPOSE OR NON INFRINGEMENT CONCERNING THIS
# SOFTWARE.
#
# ================================
#
# $Id: Makefile,v 1.3 2006/04/15 03:48:28 honor Exp $
#

CFLAGS += -I$(TOPDIR)/../..
CFLAGS += -I$(TOPDIR)/../../include
obj-m           += ctmisc.o
ctmisc-objs     := flash.o misc.o
