# ================================
#
# Copyright (C) 2009 - 2010, CyberTAN Corporation
#
#
#
# All Rights Reserved.
#
# You can redistribute it and/or modify it under the terms of the GPL v2
#
#
# THIS SOFTWARE IS OFFERED "AS IS", AND CYBERTAN GRANTS NO WARRANTIES OF ANY
# KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE.
#
# CYBERTAN SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A SPECIFIC PURPOSE OR NON INFRINGEMENT CONCERNING THIS
# SOFTWARE.
#
# $Id: Makefile,v 1.1.12.1 2009/01/15 09:36:31 jack Exp $
#

CFLAGS += -I$(TOPDIR)/../..
CFLAGS += -I$(TOPDIR)/../../include
obj-m           += ctbootnv.o
ctbootnv-objs     := bootnv.o flash.o
