# **************************************************************
# Makefile for building the IGMP Proxy module.
#	Build Targets
#		all 	- Builds the IGMP Proxy executable. igmpxmld
#		clean 	- Cleans all the object files.
# **************************************************************

all:

clean:
	rm -rf $(OBJECTS)

install:

