cmd_arch/mips/brcm-boards/generic/int-handler.o := mipsel-uclibc-linux26-gcc -Wp,-MD,arch/mips/brcm-boards/generic/.int-handler.o.d  -nostdinc -isystem /projects/hnd/tools/linux/hndtools-mipsel-linux-uclibc-4.2.3/lib/gcc/mipsel-linux-uclibc/4.2.3/include -D__KERNEL__ -Iinclude  -include include/linux/autoconf.h -D__ASSEMBLY__ -I../../include  -mabi=32 -G 0 -mno-abicalls -fno-pic -pipe -msoft-float -ggdb -ffreestanding  -march=mips32 -Wa,-mips32 -Wa,--trap  -Iinclude/asm-mips/mach-generic    -c -o arch/mips/brcm-boards/generic/int-handler.o arch/mips/brcm-boards/generic/int-handler.S

deps_arch/mips/brcm-boards/generic/int-handler.o := \
  arch/mips/brcm-boards/generic/int-handler.S \
  include/linux/config.h \
    $(wildcard include/config/h.h) \
    $(wildcard include/config/ipv6.h) \
    $(wildcard include/config/pppoe.h) \
    $(wildcard include/config/net/cls/tcindex.h) \
  include/linux/../../../../cy_conf.h \
    $(wildcard include/config/dnsmasq.h) \
    $(wildcard include/config/dnsmasq//.h) \
    $(wildcard include/config/udhcpd.h) \
    $(wildcard include/config/udhcpd//.h) \
    $(wildcard include/config/udhcpc.h) \
    $(wildcard include/config/udhcpc//.h) \
    $(wildcard include/config/pppoe//.h) \
    $(wildcard include/config/pptp.h) \
    $(wildcard include/config/pptp//.h) \
    $(wildcard include/config/pptp/dhcpc.h) \
    $(wildcard include/config/pptp/dhcpc//.h) \
    $(wildcard include/config/l2tp.h) \
    $(wildcard include/config/l2tp//.h) \
    $(wildcard include/config/pppd.h) \
    $(wildcard include/config/pppd//.h) \
    $(wildcard include/config/routed.h) \
    $(wildcard include/config/routed//.h) \
    $(wildcard include/config/zebra.h) \
    $(wildcard include/config/zebra//.h) \
    $(wildcard include/config/tftpd.h) \
    $(wildcard include/config/tftpd//.h) \
    $(wildcard include/config/ddns.h) \
    $(wildcard include/config/ddns//.h) \
    $(wildcard include/config/tzo/web/client2.h) \
    $(wildcard include/config/tzo/web/client2//.h) \
    $(wildcard include/config/cron.h) \
    $(wildcard include/config/cron//.h) \
    $(wildcard include/config/httpd.h) \
    $(wildcard include/config/httpd//.h) \
    $(wildcard include/config/get/post.h) \
    $(wildcard include/config/get/post//.h) \
    $(wildcard include/config/custom404.h) \
    $(wildcard include/config/custom404//.h) \
    $(wildcard include/config/trendmicro/sss.h) \
    $(wildcard include/config/trendmicro/sss//.h) \
    $(wildcard include/config/hnap.h) \
    $(wildcard include/config/hnap//.h) \
    $(wildcard include/config/hnap/ssdpdiscovery.h) \
    $(wildcard include/config/hnap/ssdpdiscovery//.h) \
    $(wildcard include/config/hnap/spec/v11.h) \
    $(wildcard include/config/hnap/spec/v11//.h) \
    $(wildcard include/config/hnap/spec/v12.h) \
    $(wildcard include/config/hnap/spec/v12//.h) \
    $(wildcard include/config/hnap/dhcp/reservations.h) \
    $(wildcard include/config/hnap/dhcp/reservations//.h) \
    $(wildcard include/config/expat.h) \
    $(wildcard include/config/expat//.h) \
    $(wildcard include/config/heartbeat.h) \
    $(wildcard include/config/heartbeat//.h) \
    $(wildcard include/config/https.h) \
    $(wildcard include/config/https//.h) \
    $(wildcard include/config/multicast.h) \
    $(wildcard include/config/multicast//.h) \
    $(wildcard include/config/igmp/x/mld.h) \
    $(wildcard include/config/igmp/x/mld//.h) \
    $(wildcard include/config/igmpv3.h) \
    $(wildcard include/config/igmpv3//.h) \
    $(wildcard include/config/igmp/hosttrack.h) \
    $(wildcard include/config/igmp/hosttrack//.h) \
    $(wildcard include/config/setup/wizard.h) \
    $(wildcard include/config/setup/wizard//.h) \
    $(wildcard include/config/push/button/test.h) \
    $(wildcard include/config/push/button/test//.h) \
    $(wildcard include/config/single/forward.h) \
    $(wildcard include/config/single/forward//.h) \
    $(wildcard include/config/udhcpd/static.h) \
    $(wildcard include/config/udhcpd/static//.h) \
    $(wildcard include/config/xbox.h) \
    $(wildcard include/config/xbox//.h) \
    $(wildcard include/config/backup/restore.h) \
    $(wildcard include/config/backup/restore//.h) \
    $(wildcard include/config/port/trigger.h) \
    $(wildcard include/config/port/trigger//.h) \
    $(wildcard include/config/hw/qos.h) \
    $(wildcard include/config/hw/qos//.h) \
    $(wildcard include/config/sw/qos.h) \
    $(wildcard include/config/sw/qos//.h) \
    $(wildcard include/config/write/mac.h) \
    $(wildcard include/config/write/mac//.h) \
    $(wildcard include/config/write/sn.h) \
    $(wildcard include/config/write/sn//.h) \
    $(wildcard include/config/write/country.h) \
    $(wildcard include/config/write/country//.h) \
    $(wildcard include/config/write/pa.h) \
    $(wildcard include/config/write/pa//.h) \
    $(wildcard include/config/bootnv.h) \
    $(wildcard include/config/bootnv//.h) \
    $(wildcard include/config/mfgtest.h) \
    $(wildcard include/config/mfgtest//.h) \
    $(wildcard include/config/diag.h) \
    $(wildcard include/config/diag//.h) \
    $(wildcard include/config/boot/dhcpd.h) \
    $(wildcard include/config/boot/dhcpd//.h) \
    $(wildcard include/config/boot/httpd.h) \
    $(wildcard include/config/boot/httpd//.h) \
    $(wildcard include/config/wireless.h) \
    $(wildcard include/config/wireless//.h) \
    $(wildcard include/config/eou.h) \
    $(wildcard include/config/eou//.h) \
    $(wildcard include/config/wcn.h) \
    $(wildcard include/config/wcn//.h) \
    $(wildcard include/config/wcn2.h) \
    $(wildcard include/config/wcn2//.h) \
    $(wildcard include/config/wsc.h) \
    $(wildcard include/config/wsc//.h) \
    $(wildcard include/config/write/wsc/pin.h) \
    $(wildcard include/config/write/wsc/pin//.h) \
    $(wildcard include/config/wsc/c.h) \
    $(wildcard include/config/wsc/c//.h) \
    $(wildcard include/config/wsc/cplus.h) \
    $(wildcard include/config/wsc/cplus//.h) \
    $(wildcard include/config/xyssl.h) \
    $(wildcard include/config/xyssl//.h) \
    $(wildcard include/config/polarssl.h) \
    $(wildcard include/config/polarssl//.h) \
    $(wildcard include/config/ezc.h) \
    $(wildcard include/config/ezc//.h) \
    $(wildcard include/config/ses.h) \
    $(wildcard include/config/ses//.h) \
    $(wildcard include/config/ses/button.h) \
    $(wildcard include/config/ses/button//.h) \
    $(wildcard include/config/aoss.h) \
    $(wildcard include/config/aoss//.h) \
    $(wildcard include/config/speed/booster.h) \
    $(wildcard include/config/speed/booster//.h) \
    $(wildcard include/config/disable/11n/40m.h) \
    $(wildcard include/config/disable/11n/40m//.h) \
    $(wildcard include/config/wireless/5g/band.h) \
    $(wildcard include/config/wireless/5g/band//.h) \
    $(wildcard include/config/sele/dual/band.h) \
    $(wildcard include/config/sele/dual/band//.h) \
    $(wildcard include/config/simul/dual/band.h) \
    $(wildcard include/config/simul/dual/band//.h) \
    $(wildcard include/config/monitor/usb.h) \
    $(wildcard include/config/monitor/usb//.h) \
    $(wildcard include/config/multiple/login.h) \
    $(wildcard include/config/multiple/login//.h) \
    $(wildcard include/config/tinylogin.h) \
    $(wildcard include/config/tinylogin//.h) \
    $(wildcard include/config/busybox/login.h) \
    $(wildcard include/config/busybox/login//.h) \
    $(wildcard include/config/paragon/ntfs.h) \
    $(wildcard include/config/paragon/ntfs//.h) \
    $(wildcard include/config/storage.h) \
    $(wildcard include/config/storage//.h) \
    $(wildcard include/config/smb302.h) \
    $(wildcard include/config/smb302//.h) \
    $(wildcard include/config/smb3025.h) \
    $(wildcard include/config/smb3025//.h) \
    $(wildcard include/config/smb3215.h) \
    $(wildcard include/config/smb3215//.h) \
    $(wildcard include/config/nmbd/name/register.h) \
    $(wildcard include/config/nmbd/name/register//.h) \
    $(wildcard include/config/ftp.h) \
    $(wildcard include/config/ftp//.h) \
    $(wildcard include/config/vsftpd.h) \
    $(wildcard include/config/vsftpd//.h) \
    $(wildcard include/config/proftpd.h) \
    $(wildcard include/config/proftpd//.h) \
    $(wildcard include/config/media/server.h) \
    $(wildcard include/config/media/server//.h) \
    $(wildcard include/config/email/alert.h) \
    $(wildcard include/config/email/alert//.h) \
    $(wildcard include/config/printer/server.h) \
    $(wildcard include/config/printer/server//.h) \
    $(wildcard include/config/tcp/wrapper.h) \
    $(wildcard include/config/tcp/wrapper//.h) \
    $(wildcard include/config/popt.h) \
    $(wildcard include/config/popt//.h) \
    $(wildcard include/config/raid.h) \
    $(wildcard include/config/raid//.h) \
    $(wildcard include/config/gmp.h) \
    $(wildcard include/config/gmp//.h) \
    $(wildcard include/config/mkdosfs.h) \
    $(wildcard include/config/mkdosfs//.h) \
    $(wildcard include/config/dosfstools.h) \
    $(wildcard include/config/dosfstools//.h) \
    $(wildcard include/config/respart.h) \
    $(wildcard include/config/respart//.h) \
    $(wildcard include/config/archive.h) \
    $(wildcard include/config/archive//.h) \
    $(wildcard include/config/disconnect/disk.h) \
    $(wildcard include/config/disconnect/disk//.h) \
    $(wildcard include/config/user/group.h) \
    $(wildcard include/config/user/group//.h) \
    $(wildcard include/config/user/note.h) \
    $(wildcard include/config/user/note//.h) \
    $(wildcard include/config/wipedisks.h) \
    $(wildcard include/config/wipedisks//.h) \
    $(wildcard include/config/disktestwait.h) \
    $(wildcard include/config/disktestwait//.h) \
    $(wildcard include/config/secsrl.h) \
    $(wildcard include/config/secsrl//.h) \
    $(wildcard include/config/seutil.h) \
    $(wildcard include/config/seutil//.h) \
    $(wildcard include/config/nfs.h) \
    $(wildcard include/config/nfs//.h) \
    $(wildcard include/config/portmap.h) \
    $(wildcard include/config/portmap//.h) \
    $(wildcard include/config/mpppoe.h) \
    $(wildcard include/config/mpppoe//.h) \
    $(wildcard include/config/unnumberip.h) \
    $(wildcard include/config/unnumberip//.h) \
    $(wildcard include/config/ddns3322.h) \
    $(wildcard include/config/ddns3322//.h) \
    $(wildcard include/config/peanuthull.h) \
    $(wildcard include/config/peanuthull//.h) \
    $(wildcard include/config/multilang.h) \
    $(wildcard include/config/multilang//.h) \
    $(wildcard include/config/multilang/page.h) \
    $(wildcard include/config/multilang/page//.h) \
    $(wildcard include/config/multilang/gui.h) \
    $(wildcard include/config/multilang/gui//.h) \
    $(wildcard include/config/vlan.h) \
    $(wildcard include/config/vlan//.h) \
    $(wildcard include/config/parental/control.h) \
    $(wildcard include/config/parental/control//.h) \
    $(wildcard include/config/snmp.h) \
    $(wildcard include/config/snmp//.h) \
    $(wildcard include/config/hsiab.h) \
    $(wildcard include/config/hsiab//.h) \
    $(wildcard include/config/ddm.h) \
    $(wildcard include/config/ddm//.h) \
    $(wildcard include/config/utelnetd.h) \
    $(wildcard include/config/utelnetd//.h) \
    $(wildcard include/config/symc/outbreak.h) \
    $(wildcard include/config/symc/outbreak//.h) \
    $(wildcard include/config/ebtables.h) \
    $(wildcard include/config/ebtables//.h) \
    $(wildcard include/config/lltd.h) \
    $(wildcard include/config/lltd//.h) \
    $(wildcard include/config/http/simple.h) \
    $(wildcard include/config/http/simple//.h) \
    $(wildcard include/config/pciutils.h) \
    $(wildcard include/config/pciutils//.h) \
    $(wildcard include/config/wl/iocmd.h) \
    $(wildcard include/config/wl/iocmd//.h) \
    $(wildcard include/config/wl/full.h) \
    $(wildcard include/config/wl/full//.h) \
    $(wildcard include/config/syslog.h) \
    $(wildcard include/config/syslog//.h) \
    $(wildcard include/config/klogd.h) \
    $(wildcard include/config/klogd//.h) \
    $(wildcard include/config/wl/wds.h) \
    $(wildcard include/config/wl/wds//.h) \
    $(wildcard include/config/wl/sta.h) \
    $(wildcard include/config/wl/sta//.h) \
    $(wildcard include/config/wake/on/lan.h) \
    $(wildcard include/config/wake/on/lan//.h) \
    $(wildcard include/config/samba.h) \
    $(wildcard include/config/samba//.h) \
    $(wildcard include/config/upnp/forward.h) \
    $(wildcard include/config/upnp/forward//.h) \
    $(wildcard include/config/performance.h) \
    $(wildcard include/config/performance//.h) \
    $(wildcard include/config/pppoe/server.h) \
    $(wildcard include/config/pppoe/server//.h) \
    $(wildcard include/config/aol.h) \
    $(wildcard include/config/aol//.h) \
    $(wildcard include/config/emi/test.h) \
    $(wildcard include/config/emi/test//.h) \
    $(wildcard include/config/throughput/test.h) \
    $(wildcard include/config/throughput/test//.h) \
    $(wildcard include/config/for/tmobile/test.h) \
    $(wildcard include/config/for/tmobile/test//.h) \
    $(wildcard include/config/curl.h) \
    $(wildcard include/config/curl//.h) \
    $(wildcard include/config/t/mobile.h) \
    $(wildcard include/config/t/mobile//.h) \
    $(wildcard include/config/rxp.h) \
    $(wildcard include/config/rxp//.h) \
    $(wildcard include/config/t/cert.h) \
    $(wildcard include/config/t/cert//.h) \
    $(wildcard include/config/cell/vendor/test.h) \
    $(wildcard include/config/cell/vendor/test//.h) \
    $(wildcard include/config/dual/image.h) \
    $(wildcard include/config/dual/image//.h) \
    $(wildcard include/config/igmp/snoop.h) \
    $(wildcard include/config/igmp/snoop//.h) \
    $(wildcard include/config/emf.h) \
    $(wildcard include/config/emf//.h) \
    $(wildcard include/config/ipv6//.h) \
    $(wildcard include/config/radvd.h) \
    $(wildcard include/config/radvd//.h) \
    $(wildcard include/config/iproute2.h) \
    $(wildcard include/config/iproute2//.h) \
    $(wildcard include/config/iputils.h) \
    $(wildcard include/config/iputils//.h) \
    $(wildcard include/config/dhcpv6s.h) \
    $(wildcard include/config/dhcpv6s//.h) \
    $(wildcard include/config/dhcpv6c.h) \
    $(wildcard include/config/dhcpv6c//.h) \
    $(wildcard include/config/twonky.h) \
    $(wildcard include/config/twonky//.h) \
    $(wildcard include/config/boot128k.h) \
    $(wildcard include/config/boot128k//.h) \
    $(wildcard include/config/eghn.h) \
    $(wildcard include/config/eghn//.h) \
    $(wildcard include/config/three/arp/gratuatous.h) \
    $(wildcard include/config/three/arp/gratuatous//.h) \
    $(wildcard include/config/selfsign.h) \
    $(wildcard include/config/selfsign//.h) \
    $(wildcard include/config/build/mfg.h) \
    $(wildcard include/config/build/mfg//.h) \
    $(wildcard include/config/wl/app.h) \
    $(wildcard include/config/wl/app//.h) \
    $(wildcard include/config/gui/timeout.h) \
    $(wildcard include/config/gui/timeout//.h) \
    $(wildcard include/config/ipv6/security.h) \
    $(wildcard include/config/ipv6/security//.h) \
    $(wildcard include/config/alg.h) \
    $(wildcard include/config/alg/module//.h) \
    $(wildcard include/config/auto/detect/language.h) \
    $(wildcard include/config/auto/detect/language//.h) \
    $(wildcard include/config/wireless/warning/page.h) \
    $(wildcard include/config/wireless/warning/page//.h) \
    $(wildcard include/config/guest/network.h) \
    $(wildcard include/config/guest/network//.h) \
    $(wildcard include/config/hotspot.h) \
    $(wildcard include/config/hotspot//.h) \
    $(wildcard include/config/wan/detect.h) \
    $(wildcard include/config/wan/detect//.h) \
    $(wildcard include/config/ces/parental/control.h) \
    $(wildcard include/config/ces/parental/control//.h) \
    $(wildcard include/config/ces/mdns.h) \
    $(wildcard include/config/ces/mdns//.h) \
    $(wildcard include/config/ces/e/series.h) \
    $(wildcard include/config/ces/e/series//.h) \
    $(wildcard include/config/router2switch.h) \
    $(wildcard include/config/router2switch//.h) \
    $(wildcard include/config/usbap.h) \
    $(wildcard include/config/usbap//.h) \
    $(wildcard include/config/virtual/usb.h) \
    $(wildcard include/config/virtual/usb//.h) \
  include/asm/asm.h \
    $(wildcard include/config/printk.h) \
    $(wildcard include/config/cpu/has/prefetch.h) \
  include/asm/sgidefs.h \
  include/asm/mipsregs.h \
    $(wildcard include/config/cpu/vr41xx.h) \
    $(wildcard include/config/page/size/4kb.h) \
    $(wildcard include/config/page/size/16kb.h) \
    $(wildcard include/config/page/size/64kb.h) \
    $(wildcard include/config/mips/mt/smtc.h) \
  include/linux/linkage.h \
  include/asm/linkage.h \
  include/asm/hazards.h \
    $(wildcard include/config/cpu/mipsr2.h) \
    $(wildcard include/config/cpu/r10000.h) \
    $(wildcard include/config/cpu/rm9000.h) \
    $(wildcard include/config/cpu/sb1.h) \
  include/asm/regdef.h \
  include/asm/stackframe.h \
    $(wildcard include/config/cpu/r3000.h) \
    $(wildcard include/config/cpu/tx39xx.h) \
    $(wildcard include/config/cpu/has/smartmips.h) \
    $(wildcard include/config/32bit.h) \
    $(wildcard include/config/smp.h) \
    $(wildcard include/config/build/elf64.h) \
    $(wildcard include/config/64bit.h) \
    $(wildcard include/config/bcm47xx.h) \
  include/linux/threads.h \
    $(wildcard include/config/nr/cpus.h) \
    $(wildcard include/config/base/small.h) \
  include/asm/asmmacro.h \
  include/asm/asmmacro-32.h \
  include/asm/asm-offsets.h \
  include/asm/fpregdef.h \

arch/mips/brcm-boards/generic/int-handler.o: $(deps_arch/mips/brcm-boards/generic/int-handler.o)

$(deps_arch/mips/brcm-boards/generic/int-handler.o):
