name: CI build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Extract source code
      shell: bash
      run: |
        cd "Source Code"
        ./merge_and_extract.sh
        ./clean.sh

    - name: Build
      shell: bash
      run: |
        cd "Source Code"/DVRF_v03_source/
        ./make.sh
