name: CI build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install compiler
      shell: bash
      run: |
        curl -LO https://github.com/mzpqnxow/hndtools-toolchains/raw/refs/heads/master/hndtools-mipsel-linux-uclibc-4.2.3.tar.bz2
        tar -xvjf hndtools-mipsel-linux-uclibc-4.2.3.tar.bz2
        rm hndtools-mipsel-linux-uclibc-4.2.3.tar.bz2
        rm Source_Code/DVRF_v03_source/toolchain.sh
        cp Source_Code/toolchain.sh Source_Code/DVRF_v03_source/

    - name: Build
      shell: bash
      run: |
        cd Source_Code/DVRF_v03_source/
        ./make.sh
